# workflow 名字 具体的配置见  https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: My Note Build Task
# 在push *.md文件后执行任务
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    # branches:    
    #   - master
    paths:
      - '**.md'
      - '**.yml'
      - '**.yaml'
      - '**.sh'
    # tags:
    #   - build**
# on:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  build:
    # runs-on: macOS-latest
    runs-on: ubuntu-latest
    steps:
    # 输出虚拟机的环境变量, 非常有用
    - name: print env
      run: printenv
    # 引用外部Action, 拉取代码仓库到虚拟机工作目录
    - name: chekout code
      uses: actions/checkout@v1
    - name: build note
      run: sh ./build.sh  
    # 这里是一些额外的操作, 通常不需要. 这里是为了把编译好的二进制程序 push 到原始的 GitHub 仓库
    - name: commit change
      run: |
        git config --local user.email "420640763@qq.com"
        git config --local user.name "$GITHUB_ACTOR"
        echo "---------- git config --list"
        git config --list
        echo "---------- git status"
        git status
        # echo "---------- git add"
        # git add ./
        echo "---------- git commit"
        git commit -a -m "auto build task"
        echo "---------- git status"
        git status
        echo "---------- git status"
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # github_token: ${{ secrets.ALL_ACCESS }}